# oerc configuration file
# db settings (sqlite)
DbType: sqlite
DbHost: ~/.oerc.db
DbPort:
DbName: oerc_db
DbSchema: public
DbUser:
DbPassword:
DbSSLEnabled: false
ForceUpdate: false
TimeToRefreshInMinutes: 360
DaysInPast: 2
DaysInFuture: 7
EnableARD: true
EnableZDF: true
EnableORF: true
EnableSRF: true
EnableProgramEntryCollection: true
EnableTVShowCollection: true
ProxyUrl:
TimeZone: Europe/Berlin
# backend server settings
ServerHost: 127.0.0.1
ServerPort: 8080
# client server settings
ClientEnabled: true
# search settings
SearchDaysInFuture: 5
# feel free to compose the following list of keywords as you want. They are used case-insensitive.
SearchKeywords:
  - Loriot
SearchSkipChannels:
  - KIKA
  - ORF Sport +
# if you don't know what this means, you should probably keep this value
AccessControlAllowOrigin: "http://127.0.0.1:8080"
