# db settings
DbType: postgres
DbHost: localhost
DbPort: 5432
DbName: oer_server_dev
DbSchema: public
DbUser: postgres
DbPassword: root
DbSSLEnabled: false
# general fetch settings
Debug: true
ProfilingEnabled: false
ForceUpdate: false
TimeToRefreshInMinutes: 360
DaysInPast: 2
DaysInFuture: 2
EnableARD: true
EnableZDF: true
EnableORF: true
EnableSRF: true
EnableProgramEntryCollection: true
EnableTVShowCollection: true
ProxyUrl:
TimeZone: Europe/Berlin
# backend server settings
ServerHost: 127.0.0.1
ServerPort: 8080
# client server settings
ClientEnabled: true
# search settings
SearchDaysInFuture: 5
SearchKeywords:
  - Loriot
  - Garten
SearchSkipChannels:
  - KIKA
  - ORF Sport +
AccessControlAllowOrigin: "http://127.0.0.1:8080"